# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from typing import Dict, List, Union, Optional
from typing_extensions import Literal, Annotated, TypeAlias

from .._utils import PropertyInfo
from .._models import BaseModel

__all__ = [
    "Message",
    "Content",
    "ContentMessageOutputTextBlock",
    "ContentMessageOutputToolUseBlock",
    "ContentMessageOutputThinkingBlock",
    "ContentMessageOutputRedactedThinkingBlock",
    "ContentMessageOutputServerToolUseBlock",
    "ContentMessageOutputWebSearchToolResultBlock",
    "ContentMessageOutputWebFetchToolResultBlock",
    "ContentMessageOutputCodeExecutionToolResultBlock",
    "ContentMessageOutputBashCodeExecutionToolResultBlock",
    "ContentMessageOutputTextEditorCodeExecutionToolResultBlock",
    "ContentMessageOutputToolSearchToolResultBlock",
    "ContentMessageOutputContainerUploadBlock",
    "Usage",
    "Container",
    "StopDetails",
]


class ContentMessageOutputTextBlock(BaseModel):
    """Plain-text segment of the model's response."""

    text: str

    type: Literal["text"]

    citations: Optional[List[Dict[str, object]]] = None
    """Not emitted in v1."""


class ContentMessageOutputToolUseBlock(BaseModel):
    """Tool call generated by the model."""

    id: str
    """Unique identifier for this tool call."""

    input: Dict[str, object]
    """Tool inputs as a JSON object."""

    name: str
    """Name of the tool being called."""

    type: Literal["tool_use"]

    caller: Optional[Dict[str, object]] = None
    """Anthropic routing metadata. Always `null` in SambaNova responses."""


class ContentMessageOutputThinkingBlock(BaseModel):
    """Extended-reasoning trace from the model. Emitted by reasoning models."""

    thinking: str

    type: Literal["thinking"]

    signature: Optional[str] = None


class ContentMessageOutputRedactedThinkingBlock(BaseModel):
    """
    Anthropic compatibility only — SambaNova does not produce encrypted thinking output. Never emitted in responses.
    """

    data: str

    type: Literal["redacted_thinking"]


class ContentMessageOutputServerToolUseBlock(BaseModel):
    """Anthropic compatibility only — SambaNova does not run server-side tools.

    Never emitted in responses; defined for Anthropic SDK type-parity.
    """

    id: str

    input: Dict[str, object]

    name: str

    type: Literal["server_tool_use"]


class ContentMessageOutputWebSearchToolResultBlock(BaseModel):
    """Anthropic compatibility only — SambaNova does not run server-side `web_search`.

    Never emitted in responses.
    """

    content: List[Dict[str, object]]

    tool_use_id: str

    type: Literal["web_search_tool_result"]


class ContentMessageOutputWebFetchToolResultBlock(BaseModel):
    """Anthropic compatibility only — SambaNova does not run server-side `web_fetch`.

    Never emitted in responses.
    """

    content: Dict[str, object]

    tool_use_id: str

    type: Literal["web_fetch_tool_result"]


class ContentMessageOutputCodeExecutionToolResultBlock(BaseModel):
    """
    Anthropic compatibility only — SambaNova does not run server-side `code_execution`. Never emitted in responses.
    """

    content: Dict[str, object]

    tool_use_id: str

    type: Literal["code_execution_tool_result"]


class ContentMessageOutputBashCodeExecutionToolResultBlock(BaseModel):
    """
    Anthropic compatibility only — SambaNova does not run server-side bash code execution. Never emitted in responses.
    """

    content: Dict[str, object]

    tool_use_id: str

    type: Literal["bash_code_execution_tool_result"]


class ContentMessageOutputTextEditorCodeExecutionToolResultBlock(BaseModel):
    """
    Anthropic compatibility only — SambaNova does not run server-side text-editor code execution. Never emitted in responses.
    """

    content: Dict[str, object]

    tool_use_id: str

    type: Literal["text_editor_code_execution_tool_result"]


class ContentMessageOutputToolSearchToolResultBlock(BaseModel):
    """Anthropic compatibility only — SambaNova does not run server-side `tool_search`.

    Never emitted in responses.
    """

    content: Dict[str, object]

    tool_use_id: str

    type: Literal["tool_search_tool_result"]


class ContentMessageOutputContainerUploadBlock(BaseModel):
    """
    Anthropic compatibility only — SambaNova does not produce container_upload blocks (these come from Anthropic's server-side `code_execution` tool). Never emitted in responses.
    """

    file_id: str

    type: Literal["container_upload"]


Content: TypeAlias = Annotated[
    Union[
        ContentMessageOutputTextBlock,
        ContentMessageOutputToolUseBlock,
        ContentMessageOutputThinkingBlock,
        ContentMessageOutputRedactedThinkingBlock,
        ContentMessageOutputServerToolUseBlock,
        ContentMessageOutputWebSearchToolResultBlock,
        ContentMessageOutputWebFetchToolResultBlock,
        ContentMessageOutputCodeExecutionToolResultBlock,
        ContentMessageOutputBashCodeExecutionToolResultBlock,
        ContentMessageOutputTextEditorCodeExecutionToolResultBlock,
        ContentMessageOutputToolSearchToolResultBlock,
        ContentMessageOutputContainerUploadBlock,
    ],
    PropertyInfo(discriminator="type"),
]


class Usage(BaseModel):
    """Token accounting for the request."""

    input_tokens: int
    """Total tokens in the prompt (system + messages + tools)."""

    output_tokens: int
    """Total tokens generated by the model."""

    cache_creation: Optional[Dict[str, object]] = None
    """Anthropic SDK alias for cache write metrics.

    Always `null` in SambaNova responses; use `cache_creation_input_tokens` instead.
    """

    cache_creation_input_tokens: Optional[int] = None
    """Tokens written to prompt cache.

    Absent in v1; emitted once prompt caching wiring lands (CP-2897).
    """

    cache_read_input_tokens: Optional[int] = None
    """Tokens read from prompt cache.

    Absent in v1; emitted once prompt caching wiring lands (CP-2897).
    """

    inference_geo: Optional[str] = None
    """Geographic region that served the request.

    Anthropic compatibility only - SambaNova does not expose geo routing, always
    `null`.
    """

    server_tool_use: Optional[Dict[str, object]] = None
    """Server-tool usage metrics (e.g.

    `web_search_requests`). Anthropic compatibility only — SambaNova does not run
    server tools, so this field is never emitted.
    """

    service_tier: Optional[str] = None
    """Service tier that processed the request.

    Anthropic compatibility only — SambaNova is single-tier and never emits this
    field.
    """


class Container(BaseModel):
    """Code-execution container reference.

    Anthropic compatibility only — SambaNova does not run server-side code execution, so this field is never emitted on responses.
    """

    id: str

    expires_at: str
    """ISO-8601 timestamp."""


class StopDetails(BaseModel):
    """Refusal stop details.

    Anthropic compatibility only — `refusal` is never emitted as a stop_reason by SambaNova (content filtering is not exposed at the API layer).
    """

    type: Literal["refusal"]

    category: Optional[Literal["cyber", "bio"]] = None


class Message(BaseModel):
    """Non-streaming response from `POST /messages`.

    Wire-compatible with the official Anthropic Messages API.
    """

    id: str
    """Unique identifier for this message."""

    content: List[Content]

    model: str
    """Model that produced the response."""

    role: Literal["assistant"]

    stop_reason: Optional[
        Literal[
            "end_turn",
            "max_tokens",
            "tool_use",
            "pause_turn",
            "refusal",
            "stop_sequence",
            "model_context_window_exceeded",
        ]
    ] = None
    """Reason the model stopped generating.

    SambaNova emits `end_turn`, `max_tokens`, `tool_use`, and `stop_sequence`. The
    remaining values are defined for Anthropic SDK type-parity but never returned:
    `pause_turn` (server-tool loop limit, not produced); `refusal` (content filter,
    not exposed); `model_context_window_exceeded` (folded to `max_tokens`).
    """

    type: Literal["message"]

    usage: Usage
    """Token accounting for the request."""

    container: Optional[Container] = None
    """Code-execution container reference.

    Anthropic compatibility only — SambaNova does not run server-side code
    execution, so this field is never emitted on responses.
    """

    stop_details: Optional[StopDetails] = None
    """Refusal stop details.

    Anthropic compatibility only — `refusal` is never emitted as a stop_reason by
    SambaNova (content filtering is not exposed at the API layer).
    """

    stop_sequence: Optional[str] = None
    """The matched stop sequence that triggered termination.

    Present when `stop_reason` is `stop_sequence`; `null` otherwise.
    """
