# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from typing import Dict, List, Union, Optional
from typing_extensions import Literal, Annotated, TypeAlias

from .._utils import PropertyInfo
from .message import Message
from .._models import BaseModel

__all__ = [
    "MessageCreateResponse",
    "MessageStartEvent",
    "MessageContentBlockStartEvent",
    "MessageContentBlockStartEventContentBlock",
    "MessageContentBlockStartEventContentBlockMessageOutputTextBlock",
    "MessageContentBlockStartEventContentBlockMessageOutputToolUseBlock",
    "MessageContentBlockStartEventContentBlockMessageOutputThinkingBlock",
    "MessageContentBlockStartEventContentBlockMessageOutputRedactedThinkingBlock",
    "MessageContentBlockStartEventContentBlockMessageOutputServerToolUseBlock",
    "MessageContentBlockStartEventContentBlockMessageOutputWebSearchToolResultBlock",
    "MessageContentBlockStartEventContentBlockMessageOutputWebFetchToolResultBlock",
    "MessageContentBlockStartEventContentBlockMessageOutputCodeExecutionToolResultBlock",
    "MessageContentBlockStartEventContentBlockMessageOutputBashCodeExecutionToolResultBlock",
    "MessageContentBlockStartEventContentBlockMessageOutputTextEditorCodeExecutionToolResultBlock",
    "MessageContentBlockStartEventContentBlockMessageOutputToolSearchToolResultBlock",
    "MessageContentBlockStartEventContentBlockMessageOutputContainerUploadBlock",
    "MessageContentBlockDeltaEvent",
    "MessageContentBlockDeltaEventDelta",
    "MessageContentBlockDeltaEventDeltaMessageContentBlockTextDelta",
    "MessageContentBlockDeltaEventDeltaMessageContentBlockInputJsonDelta",
    "MessageContentBlockDeltaEventDeltaMessageContentBlockThinkingDelta",
    "MessageContentBlockDeltaEventDeltaMessageContentBlockSignatureDelta",
    "MessageContentBlockStopEvent",
    "MessageDeltaEvent",
    "MessageDeltaEventDelta",
    "MessageDeltaEventDeltaStopDetails",
    "MessageDeltaEventUsage",
    "MessageStopEvent",
    "MessagePingEvent",
    "MessageStreamErrorEvent",
    "MessageStreamErrorEventError",
]


class MessageStartEvent(BaseModel):
    """First event of a stream.

    Carries the initial Message envelope (empty `content[]`, `stop_reason: null`) and token usage from prompt processing.
    """

    message: Message
    """Non-streaming response from `POST /messages`.

    Wire-compatible with the official Anthropic Messages API.
    """

    type: Literal["message_start"]


class MessageContentBlockStartEventContentBlockMessageOutputTextBlock(BaseModel):
    """Plain-text segment of the model's response."""

    text: str

    type: Literal["text"]

    citations: Optional[List[Dict[str, object]]] = None
    """Not emitted in v1."""


class MessageContentBlockStartEventContentBlockMessageOutputToolUseBlock(BaseModel):
    """Tool call generated by the model."""

    id: str
    """Unique identifier for this tool call."""

    input: Dict[str, object]
    """Tool inputs as a JSON object."""

    name: str
    """Name of the tool being called."""

    type: Literal["tool_use"]

    caller: Optional[Dict[str, object]] = None
    """Anthropic routing metadata. Always `null` in SambaNova responses."""


class MessageContentBlockStartEventContentBlockMessageOutputThinkingBlock(BaseModel):
    """Extended-reasoning trace from the model. Emitted by reasoning models."""

    thinking: str

    type: Literal["thinking"]

    signature: Optional[str] = None


class MessageContentBlockStartEventContentBlockMessageOutputRedactedThinkingBlock(BaseModel):
    """
    Anthropic compatibility only — SambaNova does not produce encrypted thinking output. Never emitted in responses.
    """

    data: str

    type: Literal["redacted_thinking"]


class MessageContentBlockStartEventContentBlockMessageOutputServerToolUseBlock(BaseModel):
    """Anthropic compatibility only — SambaNova does not run server-side tools.

    Never emitted in responses; defined for Anthropic SDK type-parity.
    """

    id: str

    input: Dict[str, object]

    name: str

    type: Literal["server_tool_use"]


class MessageContentBlockStartEventContentBlockMessageOutputWebSearchToolResultBlock(BaseModel):
    """Anthropic compatibility only — SambaNova does not run server-side `web_search`.

    Never emitted in responses.
    """

    content: List[Dict[str, object]]

    tool_use_id: str

    type: Literal["web_search_tool_result"]


class MessageContentBlockStartEventContentBlockMessageOutputWebFetchToolResultBlock(BaseModel):
    """Anthropic compatibility only — SambaNova does not run server-side `web_fetch`.

    Never emitted in responses.
    """

    content: Dict[str, object]

    tool_use_id: str

    type: Literal["web_fetch_tool_result"]


class MessageContentBlockStartEventContentBlockMessageOutputCodeExecutionToolResultBlock(BaseModel):
    """
    Anthropic compatibility only — SambaNova does not run server-side `code_execution`. Never emitted in responses.
    """

    content: Dict[str, object]

    tool_use_id: str

    type: Literal["code_execution_tool_result"]


class MessageContentBlockStartEventContentBlockMessageOutputBashCodeExecutionToolResultBlock(BaseModel):
    """
    Anthropic compatibility only — SambaNova does not run server-side bash code execution. Never emitted in responses.
    """

    content: Dict[str, object]

    tool_use_id: str

    type: Literal["bash_code_execution_tool_result"]


class MessageContentBlockStartEventContentBlockMessageOutputTextEditorCodeExecutionToolResultBlock(BaseModel):
    """
    Anthropic compatibility only — SambaNova does not run server-side text-editor code execution. Never emitted in responses.
    """

    content: Dict[str, object]

    tool_use_id: str

    type: Literal["text_editor_code_execution_tool_result"]


class MessageContentBlockStartEventContentBlockMessageOutputToolSearchToolResultBlock(BaseModel):
    """Anthropic compatibility only — SambaNova does not run server-side `tool_search`.

    Never emitted in responses.
    """

    content: Dict[str, object]

    tool_use_id: str

    type: Literal["tool_search_tool_result"]


class MessageContentBlockStartEventContentBlockMessageOutputContainerUploadBlock(BaseModel):
    """
    Anthropic compatibility only — SambaNova does not produce container_upload blocks (these come from Anthropic's server-side `code_execution` tool). Never emitted in responses.
    """

    file_id: str

    type: Literal["container_upload"]


MessageContentBlockStartEventContentBlock: TypeAlias = Annotated[
    Union[
        MessageContentBlockStartEventContentBlockMessageOutputTextBlock,
        MessageContentBlockStartEventContentBlockMessageOutputToolUseBlock,
        MessageContentBlockStartEventContentBlockMessageOutputThinkingBlock,
        MessageContentBlockStartEventContentBlockMessageOutputRedactedThinkingBlock,
        MessageContentBlockStartEventContentBlockMessageOutputServerToolUseBlock,
        MessageContentBlockStartEventContentBlockMessageOutputWebSearchToolResultBlock,
        MessageContentBlockStartEventContentBlockMessageOutputWebFetchToolResultBlock,
        MessageContentBlockStartEventContentBlockMessageOutputCodeExecutionToolResultBlock,
        MessageContentBlockStartEventContentBlockMessageOutputBashCodeExecutionToolResultBlock,
        MessageContentBlockStartEventContentBlockMessageOutputTextEditorCodeExecutionToolResultBlock,
        MessageContentBlockStartEventContentBlockMessageOutputToolSearchToolResultBlock,
        MessageContentBlockStartEventContentBlockMessageOutputContainerUploadBlock,
    ],
    PropertyInfo(discriminator="type"),
]


class MessageContentBlockStartEvent(BaseModel):
    """Opens a new content block. One per block in `content[]`."""

    content_block: MessageContentBlockStartEventContentBlock
    """Typed content block in the model's response."""

    index: int
    """Zero-based index of the block within `content[]`."""

    type: Literal["content_block_start"]


class MessageContentBlockDeltaEventDeltaMessageContentBlockTextDelta(BaseModel):
    """Incremental text chunk for an open text content block."""

    text: str

    type: Literal["text_delta"]


class MessageContentBlockDeltaEventDeltaMessageContentBlockInputJsonDelta(BaseModel):
    """Incremental fragment of a tool_use block's `input` JSON.

    Concatenate successive `partial_json` strings to reconstruct the full input object.
    """

    partial_json: str

    type: Literal["input_json_delta"]


class MessageContentBlockDeltaEventDeltaMessageContentBlockThinkingDelta(BaseModel):
    """Incremental thinking chunk for an open thinking block.

    Emitted by reasoning models.
    """

    thinking: str

    type: Literal["thinking_delta"]


class MessageContentBlockDeltaEventDeltaMessageContentBlockSignatureDelta(BaseModel):
    """Signature for an open thinking block.

    Emitted at the end of a thinking stream (paired with the closing `content_block_stop`); the `signature` value may be an empty string when the backend has no signed payload to attach.
    """

    signature: str

    type: Literal["signature_delta"]


MessageContentBlockDeltaEventDelta: TypeAlias = Annotated[
    Union[
        MessageContentBlockDeltaEventDeltaMessageContentBlockTextDelta,
        MessageContentBlockDeltaEventDeltaMessageContentBlockInputJsonDelta,
        MessageContentBlockDeltaEventDeltaMessageContentBlockThinkingDelta,
        MessageContentBlockDeltaEventDeltaMessageContentBlockSignatureDelta,
    ],
    PropertyInfo(discriminator="type"),
]


class MessageContentBlockDeltaEvent(BaseModel):
    """Incremental update to the currently open content block."""

    delta: MessageContentBlockDeltaEventDelta
    """Incremental update to an open content block."""

    index: int
    """Zero-based index of the block within `content[]`."""

    type: Literal["content_block_delta"]


class MessageContentBlockStopEvent(BaseModel):
    """Closes the current content block."""

    index: int
    """Zero-based index of the block within `content[]`."""

    type: Literal["content_block_stop"]


class MessageDeltaEventDeltaStopDetails(BaseModel):
    """Refusal stop details.

    Anthropic compatibility only — `refusal` is never emitted as a stop_reason by SambaNova (content filtering is not exposed at the API layer).
    """

    type: Literal["refusal"]

    category: Optional[Literal["cyber", "bio"]] = None


class MessageDeltaEventDelta(BaseModel):
    stop_reason: Literal[
        "end_turn", "max_tokens", "tool_use", "pause_turn", "refusal", "stop_sequence", "model_context_window_exceeded"
    ]
    """Reason the model stopped generating.

    SambaNova emits `end_turn`, `max_tokens`, `tool_use`, and `stop_sequence`. The
    remaining values are defined for Anthropic SDK type-parity but never returned:
    `pause_turn` (server-tool loop limit, not produced); `refusal` (content filter,
    not exposed); `model_context_window_exceeded` (folded to `max_tokens`).
    """

    stop_details: Optional[MessageDeltaEventDeltaStopDetails] = None
    """Refusal stop details.

    Anthropic compatibility only — `refusal` is never emitted as a stop_reason by
    SambaNova (content filtering is not exposed at the API layer).
    """

    stop_sequence: Optional[str] = None
    """Custom stop sequence that triggered termination.

    Field is emitted but value is always `null` in v1 (backend collapses
    `StopSequenceHit` and `EndOfText` into the same finish_reason).
    """


class MessageDeltaEventUsage(BaseModel):
    """
    Final token accounting emitted in the closing `message_delta` event of a stream.
    """

    output_tokens: int
    """Total tokens generated (final count)."""

    cache_creation_input_tokens: Optional[int] = None
    """Tokens written to prompt cache. Absent in v1;"""

    cache_read_input_tokens: Optional[int] = None
    """Tokens read from prompt cache. Absent in v1;"""

    input_tokens: Optional[int] = None
    """Total tokens in the prompt (echoed from `message_start`)."""

    server_tool_use: Optional[Dict[str, object]] = None
    """Server-tool usage metrics.

    Anthropic compatibility only — SambaNova does not run server tools, so this
    field is never emitted.
    """


class MessageDeltaEvent(BaseModel):
    """Penultimate event of the stream.

    Carries the final `stop_reason`, optional `stop_sequence`, and final usage counts.
    """

    delta: MessageDeltaEventDelta

    type: Literal["message_delta"]

    usage: MessageDeltaEventUsage
    """
    Final token accounting emitted in the closing `message_delta` event of a stream.
    """


class MessageStopEvent(BaseModel):
    """Final event of the stream. No fields beyond `type`."""

    type: Literal["message_stop"]


class MessagePingEvent(BaseModel):
    """Keepalive heartbeat. May appear at any point in the stream."""

    type: Literal["ping"]


class MessageStreamErrorEventError(BaseModel):
    """Inner error object carried inside a `MessageErrorResponse`.

    The `type` value follows Anthropic's published error taxonomy.
    """

    message: str
    """Human-readable explanation of the error."""

    type: Literal[
        "invalid_request_error",
        "authentication_error",
        "permission_error",
        "not_found_error",
        "request_too_large",
        "rate_limit_error",
        "api_error",
        "overloaded_error",
        "not_implemented_error",
    ]
    """Error category. Values follow Anthropic's taxonomy."""


class MessageStreamErrorEvent(BaseModel):
    """Streamed error envelope. Terminates the stream."""

    error: MessageStreamErrorEventError
    """Inner error object carried inside a `MessageErrorResponse`.

    The `type` value follows Anthropic's published error taxonomy.
    """

    type: Literal["error"]


MessageCreateResponse: TypeAlias = Union[
    Message,
    MessageStartEvent,
    MessageContentBlockStartEvent,
    MessageContentBlockDeltaEvent,
    MessageContentBlockStopEvent,
    MessageDeltaEvent,
    MessageStopEvent,
    MessagePingEvent,
    MessageStreamErrorEvent,
]
